apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-aip2
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sqsu-tenant/status-quarkus-io/statusquarkusio-aip2@sha256:b9ef7534069a7e4a31f6fd0ec5099467c901dc8c332a51379bdc4596451b446e
        name: my-java-quarkus
        resources: {}
status: {}
